#!/usr/bin/env python3
"""
Generate vanity URL redirect pages from _data/redirects.yml.

Reads the centralized redirects config, generates minimal Jekyll redirect
pages, and validates that no vanity URLs conflict with existing site pages,
blog posts, or each other.

Usage:
    python scripts/generate_redirects.py          # from project root
    python scripts/generate_redirects.py --clean   # also remove stale redirect files
"""

import os
import re
import sys
import glob
import argparse

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Install it with: pip install pyyaml")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Paths (relative to project root)
# ---------------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
REDIRECTS_FILE = os.path.join(PROJECT_ROOT, "_data", "redirects.yml")
CONFIG_FILE = os.path.join(PROJECT_ROOT, "_config.yml")
POSTS_DIR = os.path.join(PROJECT_ROOT, "_posts")

# Marker comment embedded in generated files so the script can identify them.
GENERATED_MARKER = "# Generated by scripts/generate_redirects.py — do not edit manually."

# Directories that Jekyll reserves (not user pages).
JEKYLL_RESERVED_DIRS = {
    "_data", "_includes", "_layouts", "_posts", "_sass",
    "_site", "_plugins", "_drafts", "assets", "scripts",
    ".git", "vendor", "node_modules",
}


def load_yaml(path):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def collect_existing_page_paths():
    """Return a dict mapping URL paths to their source files for all
    non-redirect pages that Jekyll will serve."""
    paths = {}

    for filepath in glob.glob(os.path.join(PROJECT_ROOT, "*.html")):
        basename = os.path.basename(filepath)
        # Skip files that are generated redirects (they have our marker).
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read(512)
                if GENERATED_MARKER in content:
                    continue
        except OSError:
            continue

        name = os.path.splitext(basename)[0]
        if name == "index":
            paths["/"] = basename
        else:
            paths[f"/{name}"] = basename

    for filepath in glob.glob(os.path.join(PROJECT_ROOT, "*.md")):
        basename = os.path.basename(filepath)
        name = os.path.splitext(basename)[0]
        # Skip non-page markdown files.
        if name.upper() in ("README", "FAQ", "CONTRIBUTION", "LICENSE", "CHANGELOG"):
            continue
        paths[f"/{name}"] = basename

    return paths


def collect_post_paths(config):
    """Return a dict mapping URL paths to source files for blog posts,
    respecting the permalink pattern in _config.yml."""
    paths = {}
    permalink = config.get("permalink", "/:title/")

    if not os.path.isdir(POSTS_DIR):
        return paths

    post_pattern = re.compile(r"^(\d{4})-(\d{2})-(\d{2})-(.+)\.(md|markdown|html)$")

    for filename in os.listdir(POSTS_DIR):
        m = post_pattern.match(filename)
        if not m:
            continue
        year, month, day, slug = m.group(1), m.group(2), m.group(3), m.group(4)
        # Build the URL from the permalink pattern.
        url = permalink
        url = url.replace(":year", year)
        url = url.replace(":month", month)
        url = url.replace(":day", day)
        url = url.replace(":title", slug)
        # Normalise: ensure leading slash, strip trailing slash for comparison.
        url = "/" + url.strip("/")
        paths[url] = os.path.join("_posts", filename)

    return paths


def generate_redirect_page(redirect_entry, dry_run=False):
    """Generate a minimal Jekyll redirect HTML file for one entry."""
    from_path = redirect_entry["from"]
    filepath = os.path.join(PROJECT_ROOT, f"{from_path}.html")

    content = (
        f"---\n"
        f"{GENERATED_MARKER}\n"
        f"layout: redirect\n"
        f"redirect_key: {from_path}\n"
        f"sitemap: false\n"
        f"---\n"
    )

    if dry_run:
        return filepath, content

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath, content


def find_stale_redirects(active_from_values):
    """Find generated redirect files that are no longer in the config."""
    stale = []
    for filepath in glob.glob(os.path.join(PROJECT_ROOT, "*.html")):
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read(512)
        except OSError:
            continue
        if GENERATED_MARKER not in content:
            continue
        basename = os.path.splitext(os.path.basename(filepath))[0]
        if basename not in active_from_values:
            stale.append(filepath)
    return stale


def validate_redirects(redirects, existing_pages, post_paths):
    """Check for URL conflicts. Returns a list of warning/error strings."""
    issues = []
    seen_from = {}

    for i, entry in enumerate(redirects):
        from_path = entry.get("from", "")
        if not from_path:
            issues.append(f"ERROR: Entry {i + 1} is missing the 'from' field.")
            continue
        if not entry.get("to"):
            issues.append(f"ERROR: Entry '{from_path}' is missing the 'to' field.")

        # Check for duplicate vanity URLs.
        url_key = f"/{from_path}"
        if from_path in seen_from:
            issues.append(
                f"CONFLICT: Duplicate vanity URL '/{from_path}' — "
                f"appears at entries {seen_from[from_path]} and {i + 1}."
            )
        else:
            seen_from[from_path] = i + 1

        # Check against existing site pages.
        if url_key in existing_pages:
            source = existing_pages[url_key]
            issues.append(
                f"CONFLICT: Vanity URL '/{from_path}' overlaps with "
                f"existing page '{source}'."
            )

        # Check against blog post URLs.
        if url_key in post_paths:
            source = post_paths[url_key]
            issues.append(
                f"CONFLICT: Vanity URL '/{from_path}' overlaps with "
                f"blog post '{source}'."
            )

        # Warn about paths that match Jekyll reserved directories.
        if from_path.split("/")[0] in JEKYLL_RESERVED_DIRS:
            issues.append(
                f"WARNING: Vanity URL '/{from_path}' starts with a "
                f"Jekyll reserved directory name."
            )

    return issues


def main():
    parser = argparse.ArgumentParser(
        description="Generate vanity URL redirect pages from _data/redirects.yml"
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove redirect files that are no longer in the config.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate and show what would be generated without writing files.",
    )
    args = parser.parse_args()

    # -----------------------------------------------------------------------
    # Load config
    # -----------------------------------------------------------------------
    if not os.path.isfile(REDIRECTS_FILE):
        print(f"ERROR: Redirects file not found: {REDIRECTS_FILE}")
        sys.exit(1)

    redirects = load_yaml(REDIRECTS_FILE)
    if not redirects:
        print("No redirects defined in _data/redirects.yml.")
        sys.exit(0)

    config = {}
    if os.path.isfile(CONFIG_FILE):
        config = load_yaml(CONFIG_FILE) or {}

    # -----------------------------------------------------------------------
    # Validate
    # -----------------------------------------------------------------------
    existing_pages = collect_existing_page_paths()
    post_paths = collect_post_paths(config)
    issues = validate_redirects(redirects, existing_pages, post_paths)

    has_errors = any(msg.startswith("ERROR") or msg.startswith("CONFLICT") for msg in issues)

    if issues:
        print("=" * 60)
        print("Vanity URL Validation Results")
        print("=" * 60)
        for msg in issues:
            print(f"  {msg}")
        print("=" * 60)
        if has_errors and not args.dry_run:
            print("\nAborting: fix the issues above before generating redirect pages.")
            sys.exit(1)

    if args.dry_run:
        print("\n[Dry run] Would generate the following redirect pages:")
        for entry in redirects:
            print(f"  /{entry['from']} -> {entry['to']}")
        sys.exit(0)

    # -----------------------------------------------------------------------
    # Generate redirect pages
    # -----------------------------------------------------------------------
    active_from = set()
    for entry in redirects:
        filepath, _ = generate_redirect_page(entry)
        active_from.add(entry["from"])
        print(f"  Generated: {os.path.relpath(filepath, PROJECT_ROOT)}")

    # -----------------------------------------------------------------------
    # Clean stale redirects
    # -----------------------------------------------------------------------
    stale = find_stale_redirects(active_from)
    if stale:
        if args.clean:
            for fp in stale:
                os.remove(fp)
                print(f"  Removed stale redirect: {os.path.relpath(fp, PROJECT_ROOT)}")
        else:
            print("\nStale redirect files (run with --clean to remove):")
            for fp in stale:
                print(f"  {os.path.relpath(fp, PROJECT_ROOT)}")

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------
    print(f"\nDone. {len(redirects)} redirect(s) generated.")
    if not issues:
        print("No URL conflicts detected.")


if __name__ == "__main__":
    main()
